pipeline {
    agent any
    environment {
        IMAGE_NAME = "ci-cd-flask-demo"
        IMAGE_TAG  = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install deps') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install pytest
                pip install flask
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                . venv/bin/activate
                cd application
                pytest tests/
                '''
            }
        }
        stage('Build image') {
            steps {
                sh '''
                podman build -t $IMAGE_NAME:$IMAGE_TAG .
                '''
            }
    }
}
