---
- name: First Playbook
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 360