---
- name: Create VM  Snapshot
  hosts: localhost
  gather_facts: true
  vars:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
#  vars_files:
#    - some-credentials.yaml
  tasks:
    - name: gather facts
      debug:
        var: ansible_facts

    - name: Create a snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/{{ folder }}"
        name: "{{ guest_name }}"
        state: present
        snapshot_name: "snapshot-{{ ansible_date_time.iso8601 }}"
        description: snap1_description
        validate_certs: no   # <-- disables TLS verification
      delegate_to: localhost